ALTER TABLE "CleanMatch" ADD COLUMN IF NOT EXISTS "parserVersion" TEXT;

ALTER TABLE "CleanPlayerMatchStats" ADD COLUMN IF NOT EXISTS "botDamageIgnored" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "CleanPlayerStats" ADD COLUMN IF NOT EXISTS "botDamageIgnored" DOUBLE PRECISION NOT NULL DEFAULT 0;
